/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// A signature object consists of the KeyID used and the signature itself.
type V1beta1intotoSignature struct {
	KeyId string `json:"key_id,omitempty"`
	Signature string `json:"signature,omitempty"`
}
