/*
 * Copyright (c) 2024. Devtron Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// This corresponds to an in-toto link.
type IntotoLink struct {
	EffectiveCommand []string `json:"effective_command,omitempty"`
	Materials []IntotoLinkArtifact `json:"materials,omitempty"`
	// Products are the supply chain artifacts generated as a result of the step. The structure is identical to that of materials.
	Products []IntotoLinkArtifact `json:"products,omitempty"`
	// ByProducts are data generated as part of a software supply chain step, but are not the actual result of the step.
	Byproducts *LinkByProducts `json:"byproducts,omitempty"`
	Environment *LinkEnvironment `json:"environment,omitempty"`
}
