/*
 * Copyright (c) 2024. Devtron Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

import (
	"time"
)

// Provides information about the analysis status of a discovered resource.
type DiscoveryDiscovered struct {
	// Whether the resource is continuously analyzed.
	ContinuousAnalysis *DiscoveredContinuousAnalysis `json:"continuous_analysis,omitempty"`
	// The last time continuous analysis was done for this resource. Deprecated, do not use.
	LastAnalysisTime time.Time `json:"last_analysis_time,omitempty"`
	// The status of discovery for the resource.
	AnalysisStatus *DiscoveredAnalysisStatus `json:"analysis_status,omitempty"`
	// When an error is encountered this will contain a LocalizedMessage under details to show to the user. The LocalizedMessage is output only and populated by the API.
	AnalysisStatusError *RpcStatus `json:"analysis_status_error,omitempty"`
}
