/*
 * Copyright (c) 2024. Devtron Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas
// BuildSignatureKeyType : Public key formats.   - KEY_TYPE_UNSPECIFIED: `KeyType` is not set.  - PGP_ASCII_ARMORED: `PGP ASCII Armored` public key.  - PKIX_PEM: `PKIX PEM` public key.
type BuildSignatureKeyType string

// List of BuildSignatureKeyType
const (
	KEY_TYPE_UNSPECIFIED_BuildSignatureKeyType BuildSignatureKeyType = "KEY_TYPE_UNSPECIFIED"
	PGP_ASCII_ARMORED_BuildSignatureKeyType BuildSignatureKeyType = "PGP_ASCII_ARMORED"
	PKIX_PEM_BuildSignatureKeyType BuildSignatureKeyType = "PKIX_PEM"
)
